apiVersion: v1
kind: Pod
metadata:
  name: env variables
  labels:
    project: roboshop
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: "DevOps with AWS"
    - name: trainer
      value: "siva kumar M"

