apiVersion: v1
kind: Pod
metadata:
  name: secrets-pod
  labels:
    project: roboshop
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: secret

